apiVersion: apps/v1.0
kind: Deployment
metadata:
  name: ccproj
  labels:
    app: ccproj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ccproj
  template:
    metadata:
      labels:
        app: ccproj
    spec:
      containers:
      - name: burner-nitkumar27
        image: gcr.io/burner-nitkumar27/burner-nitkumar27:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5021
